import type { ResampledClip } from "../convert/clip.ts";
import type { Vec3 } from "../wanim/parse.ts";
import { quatToEulerZYX, RAD2DEG } from "../convert/quat.ts";

// ASCII FBX 7.4 (7400) writer for a skeletal animation: a LimbNode skeleton
// (no mesh) driven by an AnimationStack/Layer with per-bone Lcl Rotation curves
// and a Lcl Translation curve on the root (Hips). Geometry is Y-up; lengths are
// converted meters→cm so the clip imports at human scale with UnitScaleFactor=1.
//
// Rotations are written as ZYX-extracted Euler degrees (see quatToEulerZYX) with
// the default RotationOrder, which round-trips through FBX-SDK-based importers.

const FBX_TIME_SECOND = 46186158000; // FbxTime units per second
const METERS_TO_CM = 100;

const num = (n: number): string =>
  Number.isFinite(n) ? (Object.is(n, -0) ? "0" : String(n)) : "0";

const arr = (xs: ArrayLike<number>): string => {
  const parts: string[] = [];
  for (let i = 0; i < xs.length; i++) parts.push(num(xs[i] as number));
  return parts.join(",");
};

/** Keep successive Euler components within ±180° of the previous to avoid spins. */
function unwrapDegrees(values: number[]): void {
  for (let i = 1; i < values.length; i++) {
    let d = values[i] - values[i - 1];
    while (d > 180) {
      values[i] -= 360;
      d -= 360;
    }
    while (d < -180) {
      values[i] += 360;
      d += 360;
    }
  }
}

export interface WriteAnimOpts {
  /** "Take" / animation-stack name. */
  takeName?: string;
}

export function writeAnimationFbx(clip: ResampledClip, opts: WriteAnimOpts = {}): string {
  const takeName = opts.takeName ?? "Take 001";
  const { frameCount, fps, names, parents } = clip;
  const boneCount = names.length;

  // Per-frame key times (shared by every curve).
  const keyTimes = new Array<number>(frameCount);
  const tickPerFrame = FBX_TIME_SECOND / fps;
  for (let i = 0; i < frameCount; i++) keyTimes[i] = Math.round(i * tickPerFrame);
  const stopTime = keyTimes[frameCount - 1] ?? 0;

  // Precompute Euler tracks (degrees, unwrapped) per bone.
  const eulerX: number[][] = [];
  const eulerY: number[][] = [];
  const eulerZ: number[][] = [];
  for (let b = 0; b < boneCount; b++) {
    const xs = new Array<number>(frameCount);
    const ys = new Array<number>(frameCount);
    const zs = new Array<number>(frameCount);
    for (let f = 0; f < frameCount; f++) {
      const e = quatToEulerZYX(clip.localQuat[b][f]);
      xs[f] = e[0] * RAD2DEG;
      ys[f] = e[1] * RAD2DEG;
      zs[f] = e[2] * RAD2DEG;
    }
    unwrapDegrees(xs);
    unwrapDegrees(ys);
    unwrapDegrees(zs);
    eulerX.push(xs);
    eulerY.push(ys);
    eulerZ.push(zs);
  }

  // Root (Hips) translation track in cm.
  const transX = clip.localPos[0].map((p) => p[0] * METERS_TO_CM);
  const transY = clip.localPos[0].map((p) => p[1] * METERS_TO_CM);
  const transZ = clip.localPos[0].map((p) => p[2] * METERS_TO_CM);

  // ---- id allocation -----------------------------------------------------
  let nextId = 1000000;
  const id = () => ++nextId;

  const boneModelId = names.map(() => id());
  const boneAttrId = names.map(() => id());
  const stackId = id();
  const layerId = id();

  // Per bone: a rotation AnimationCurveNode (R) + 3 AnimationCurves.
  // Hips also gets a translation node + 3 curves.
  interface Channel {
    nodeId: number;
    curveIds: [number, number, number];
  }
  const rotChannels: Channel[] = names.map(() => ({
    nodeId: id(),
    curveIds: [id(), id(), id()],
  }));
  const hipsTrans: Channel = { nodeId: id(), curveIds: [id(), id(), id()] };

  const L: string[] = [];
  const w = (s = "") => L.push(s);

  // ---- header ------------------------------------------------------------
  w("; FBX 7.4.0 project file");
  w("; Generated by WANIMxFBX (https://github.com/vtoku/WANIMxFBX)");
  w("; ----------------------------------------------------------------------");
  w("");
  w("FBXHeaderExtension:  {");
  w("\tFBXHeaderVersion: 1003");
  w("\tFBXVersion: 7400");
  w("\tCreator: \"WANIMxFBX\"");
  w("}");

  // ---- global settings (Y-up, cm, frame rate) ---------------------------
  w("GlobalSettings:  {");
  w("\tVersion: 1000");
  w("\tProperties70:  {");
  w('\t\tP: "UpAxis", "int", "Integer", "",1');
  w('\t\tP: "UpAxisSign", "int", "Integer", "",1');
  w('\t\tP: "FrontAxis", "int", "Integer", "",2');
  w('\t\tP: "FrontAxisSign", "int", "Integer", "",1');
  w('\t\tP: "CoordAxis", "int", "Integer", "",0');
  w('\t\tP: "CoordAxisSign", "int", "Integer", "",1');
  w('\t\tP: "OriginalUpAxis", "int", "Integer", "",1');
  w('\t\tP: "OriginalUpAxisSign", "int", "Integer", "",1');
  w('\t\tP: "UnitScaleFactor", "double", "Number", "",1');
  w('\t\tP: "OriginalUnitScaleFactor", "double", "Number", "",1');
  w('\t\tP: "TimeMode", "enum", "", "",6');
  w(`\t\tP: "CustomFrameRate", "double", "Number", "",${num(fps)}`);
  w(`\t\tP: "TimeSpanStart", "KTime", "Time", "",0`);
  w(`\t\tP: "TimeSpanStop", "KTime", "Time", "",${stopTime}`);
  w("\t}");
  w("}");

  w("Documents:  {");
  w("\tCount: 1");
  const docId = id();
  w(`\tDocument: ${docId}, "", "Scene" {`);
  w("\t\tRootNode: 0");
  w("\t}");
  w("}");
  w("References:  {");
  w("}");

  // ---- definitions -------------------------------------------------------
  const curveNodeCount = boneCount + 1; // rotation per bone + hips translation
  const curveCount = curveNodeCount * 3;
  const totalDefs =
    1 + boneCount + boneCount + 1 + 1 + curveNodeCount + curveCount; // settings+models+attrs+stack+layer+nodes+curves

  w("Definitions:  {");
  w("\tVersion: 100");
  w(`\tCount: ${totalDefs}`);
  w('\tObjectType: "GlobalSettings" {\n\t\tCount: 1\n\t}');
  w(`\tObjectType: "Model" {\n\t\tCount: ${boneCount}\n\t}`);
  w(`\tObjectType: "NodeAttribute" {\n\t\tCount: ${boneCount}\n\t}`);
  w('\tObjectType: "AnimationStack" {\n\t\tCount: 1\n\t}');
  w('\tObjectType: "AnimationLayer" {\n\t\tCount: 1\n\t}');
  w(`\tObjectType: "AnimationCurveNode" {\n\t\tCount: ${curveNodeCount}\n\t}`);
  w(`\tObjectType: "AnimationCurve" {\n\t\tCount: ${curveCount}\n\t}`);
  w("}");

  // ---- objects -----------------------------------------------------------
  w("Objects:  {");

  // bone node attributes + models
  names.forEach((name, i) => {
    w(`\tNodeAttribute: ${boneAttrId[i]}, "NodeAttribute::", "LimbNode" {`);
    w("\t\tProperties70:  {");
    w('\t\t\tP: "Size", "double", "Number", "",1');
    w("\t\t}");
    w('\t\tTypeFlags: "Skeleton"');
    w("\t}");

    const bind: Vec3 = clip.bindPos[i];
    const tx = bind[0] * METERS_TO_CM;
    const ty = bind[1] * METERS_TO_CM;
    const tz = bind[2] * METERS_TO_CM;
    const e0x = eulerX[i][0];
    const e0y = eulerY[i][0];
    const e0z = eulerZ[i][0];

    w(`\tModel: ${boneModelId[i]}, "Model::${name}", "LimbNode" {`);
    w("\t\tVersion: 232");
    w("\t\tProperties70:  {");
    w('\t\t\tP: "InheritType", "enum", "", "",1');
    w('\t\t\tP: "DefaultAttributeIndex", "int", "Integer", "",0');
    w(`\t\t\tP: "Lcl Translation", "Lcl Translation", "", "A",${num(tx)},${num(ty)},${num(tz)}`);
    w(`\t\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",${num(e0x)},${num(e0y)},${num(e0z)}`);
    w('\t\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1');
    w("\t\t}");
    w("\t\tShading: Y");
    w('\t\tCulling: "CullingOff"');
    w("\t}");
  });

  // animation stack + layer
  w(`\tAnimationStack: ${stackId}, "AnimStack::${takeName}", "" {`);
  w("\t\tProperties70:  {");
  w(`\t\t\tP: "LocalStop", "KTime", "Time", "",${stopTime}`);
  w(`\t\t\tP: "ReferenceStop", "KTime", "Time", "",${stopTime}`);
  w("\t\t}");
  w("\t}");
  w(`\tAnimationLayer: ${layerId}, "AnimLayer::BaseLayer", "" {`);
  w("\t}");

  // helper to emit a curve node + its 3 curves
  const emitCurveNode = (
    ch: Channel,
    label: "T" | "R",
    defaults: [number, number, number],
    tracks: [number[], number[], number[]],
  ) => {
    w(`\tAnimationCurveNode: ${ch.nodeId}, "AnimCurveNode::${label}", "" {`);
    w("\t\tProperties70:  {");
    w(`\t\t\tP: "d|X", "Number", "", "A",${num(defaults[0])}`);
    w(`\t\t\tP: "d|Y", "Number", "", "A",${num(defaults[1])}`);
    w(`\t\t\tP: "d|Z", "Number", "", "A",${num(defaults[2])}`);
    w("\t\t}");
    w("\t}");
    for (let c = 0; c < 3; c++) {
      const vals = tracks[c];
      w(`\tAnimationCurve: ${ch.curveIds[c]}, "AnimCurve::", "" {`);
      w(`\t\tDefault: ${num(vals[0])}`);
      w("\t\tKeyVer: 4009");
      w(`\t\tKeyTime: *${frameCount} {`);
      w(`\t\t\ta: ${arr(keyTimes)}`);
      w("\t\t}");
      w(`\t\tKeyValueFloat: *${frameCount} {`);
      w(`\t\t\ta: ${arr(vals)}`);
      w("\t\t}");
      // one flag entry (cubic|auto) covering all keys
      w("\t\tKeyAttrFlags: *1 {");
      w("\t\t\ta: 24840");
      w("\t\t}");
      w("\t\tKeyAttrDataFloat: *4 {");
      w("\t\t\ta: 0,0,0,0");
      w("\t\t}");
      w("\t\tKeyAttrRefCount: *1 {");
      w(`\t\t\ta: ${frameCount}`);
      w("\t\t}");
      w("\t}");
    }
  };

  names.forEach((_, i) => {
    emitCurveNode(
      rotChannels[i],
      "R",
      [eulerX[i][0], eulerY[i][0], eulerZ[i][0]],
      [eulerX[i], eulerY[i], eulerZ[i]],
    );
  });
  emitCurveNode(hipsTrans, "T", [transX[0], transY[0], transZ[0]], [transX, transY, transZ]);

  w("}");

  // ---- connections -------------------------------------------------------
  w("Connections:  {");

  // skeleton hierarchy + attributes
  names.forEach((_, i) => {
    const parentId = parents[i] >= 0 ? boneModelId[parents[i]] : 0;
    w(`\tC: "OO",${boneModelId[i]},${parentId}`);
    w(`\tC: "OO",${boneAttrId[i]},${boneModelId[i]}`);
  });

  // animation graph: layer→stack, nodes→layer, curves→nodes, nodes→model props
  w(`\tC: "OO",${layerId},${stackId}`);
  const comp = ["d|X", "d|Y", "d|Z"];
  names.forEach((_, i) => {
    const ch = rotChannels[i];
    w(`\tC: "OO",${ch.nodeId},${layerId}`);
    w(`\tC: "OP",${ch.nodeId},${boneModelId[i]}, "Lcl Rotation"`);
    for (let c = 0; c < 3; c++) w(`\tC: "OP",${ch.curveIds[c]},${ch.nodeId}, "${comp[c]}"`);
  });
  // hips translation
  w(`\tC: "OO",${hipsTrans.nodeId},${layerId}`);
  w(`\tC: "OP",${hipsTrans.nodeId},${boneModelId[0]}, "Lcl Translation"`);
  for (let c = 0; c < 3; c++) w(`\tC: "OP",${hipsTrans.curveIds[c]},${hipsTrans.nodeId}, "${comp[c]}"`);
  w("}");
  w("");

  // ---- takes -------------------------------------------------------------
  w("Takes:  {");
  w(`\tCurrent: "${takeName}"`);
  w(`\tTake: "${takeName}" {`);
  w(`\t\tFileName: "${takeName.replace(/\s+/g, "_")}.tak"`);
  w(`\t\tLocalTime: 0,${stopTime}`);
  w(`\t\tReferenceTime: 0,${stopTime}`);
  w("\t}");
  w("}");
  w("");

  return L.join("\n");
}
